name: Continuous Delivery 
on:
  push:
    branches:
      - master
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - run: bundle exec cap production deploy
