name: Continuous Delivery 
on:
  push:
    branches:
      - master
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: cd deploy directry
        run: cd /var/www/rails6webAPI/
      - name: deploy-execute
        run: bin/cap production deploy
