name: Continuous Delivery 
on:
  push:
    branches:
      - master
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: cd deploy directry
        run: cd /var/www/rails6webAPI/
      - name: change user 
        run: sudo su - deploy
      - name: deploy-execute
        run: bundle exec cap production deploy
