name: Continuous Delivery 
on:
  push:
    tags:
      - staging
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - name: deploy-execute
        run: cd /var/www/rails6webAPI/ && git fetch --all && git pull && bundle exec cap production deploy
