name: Continuous Delivery 
on:
  push:
    branches:
      - staging_v2
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - name: test
        run: echo $GITHUB_REF
      - name: deploy-execute
        run: cd /var/www/rails6webAPI/ && git fetch --all && git checkout $GITHUB_REF
