name: Continuous Delivery 
on:
  push:
    branches:
      - master
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: deploy-execute
        run: cd /var/www/rails6webAPI/ && bundle exec cap production deploy && git fetch --all && git pull
