name: Continuous Delivery 
on:
  push:
    branches:
      - staging
jobs:
  production-deploy:
    name: cap production deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: cd deploy directry
        run: cd /var/www/rails6webAPI/
      - name: bundle install
        run: bundle install --path vendor/bunlde
      - name: deploy-execute
        run: bundle exec cap production deploy
